### ISSUE TITLE
Crash - Incompatability with Gravity API.

### ISSUE THREAD

**Issue by netcore10** [huskcasaca/effortless-fabric#8] opened 2022-11-24 17:02 UTC
As expected, gravity mods cause a ticking player crash. Is it possible to have compatability?

https://mclo.gs/6o4UIjl

**Comment by huskcasaca** [comment] 2022-11-25 06:38
Okay I have created a PR for the lib [polymer](https://github.com/Patbox/polymer).

**Comment by netcore10** [comment] 2022-11-25 14:03
> Okay I have created a [PR](https://github.com/Patbox/polymer/pull/49) for the lib polymer. Let's wait.
> 
> Btw, what's gravity mods?

Gravity api let's you rotate and walk at different orientations, even on cielings.
 https://modrinth.com/mod/gravity-api

**Comment by huskcasaca** [comment] 2022-11-25 22:19
Try to rebuild this [PR](https://github.com/Patbox/polymer/pull/49) and replace your polymer mod.

Not sure if there's any other buggy mods that break custom packet handling.

Btw, is the crash caused by effortless fabric?

**Comment by netcore10** [comment] 2022-11-25 23:12
> Btw, is the crash caused by effortless fabric?
It is, when i run a command to set my gravity a different direction, i crash. Probably because effortless would never expect different gravity options. I was just curious if they could work together.

 and i will test polymer as soon as I can.

**Comment by huskcasaca** [comment] 2022-11-26 00:02
Logs pls.

**Comment by netcore10** [comment] 2022-11-26 00:25
https://paste.atlauncher.com/view/8a5bc81f-28f7-46be-ac50-b06c09e622c5 Here's my client log, probably another mod if that's the case. Guess it's another easter egg hunt

**Comment by huskcasaca** [comment] 2022-11-26 00:30
Just try uninstall. The crash happen in mixins which is hard to find the root cause mods.

**Comment by netcore10** [comment] 2022-11-26 00:36
ahaha, I'll get there. I work for a small community alone so it's one of those problems i'll have to just chug through in a day. Effortless fabric (And building) is a great mod. Sorry for all the trouble.

**Comment by netcore10** [comment] 2022-12-28 19:43
Update: Still struggling to find the issue. our project is swamped with progress and other priorities, so i don't really have much time to dig anymore.

**Comment by netcore10** [comment] 2022-12-28 19:46
i think i found it! I think it's TATERZENS! https://modrinth.com/mod/taterzens

**Comment by netcore10** [comment] 2022-12-28 19:47
https://paste.atlauncher.com/view/8212a714-9668-417e-8aea-4acd79ce3da8

**Comment by netcore10** [comment] 2022-12-28 19:50
Nope. Frick, this is a tough issue

**Comment by netcore10** [comment] 2022-12-28 19:54
my last idea is it's the loader itself. (Quilt mc. Has fabric mappings to retain compatability)

**Comment by huskcasaca** [comment] 2022-12-29 11:20
Okay merged to v1.6.1

**Comment by netcore10** [comment] 2022-12-29 13:53
Is the offset when in a different rotation fixable or is it just impossible? Is it possible to turn off effortless placement so placing blocks when on different gravity is possible?

**Closed** 2022-12-29 13:56 UTC
